### ISSUE TITLE
Update DirectXTex 

### ISSUE THREAD

**Issue by iMrShadow** [HexaEngine/Hexa.NET.DirectXTex#1]
Hello!

I am using your wrapper and so far it has been a pleasure to work with! However, it's using an older version of DirectXTex (pre-June 2023), which does not support DXGI_FORMAT_A4B4G4R4_UNORM, which was added in [this update](https://github.com/microsoft/DirectXTex/releases/tag/jun2023). 

It would be nice to have this feature, since apparently it has a usage 

Thanks!

**Comment by JunaMeinhold** [comment]
Hello,

I will update it today (to [June 2024](https://github.com/microsoft/DirectXTex/releases/tag/jun2024)), but there will be a few breaking changes, I overhauled the generator, and the package id will change from HexaEngine.DirectXTex => Hexa.NET.DirectXTex,

**Comment by JunaMeinhold** [comment]
Done. I leave this issue open so you can report if everything works, I don't have time to fully test it, but at least all unit tests passed.

**Comment by iMrShadow** [comment]
I removed the older Nuget package and installed the new one. For some reason I can't use the new library despite having it installed. Even Visual Studio and VSC can't auto-find the structs.

```Hexa.NET.DirectXTex could not be found```

This is how the package reference looks like in the project, which I found odd:
```
<PackageReference Include="Hexa.NET.DirectXTex" Version="1.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

**Comment by JunaMeinhold** [comment]
the namespace changed too (using Hexa.NET.DirectXTex;) and the package is listed https://www.nuget.org/packages/Hexa.NET.DirectXTex/

**Comment by iMrShadow** [comment]
I found the issue. I removed
```
<PrivateAssets>all</PrivateAssets>
<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
```

These lines were added when I installed the package via Nuget. After removing the namespace is recognised

**Comment by JunaMeinhold** [comment]
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/2333acb2-71d4-45c5-a699-d09a0dac838b)
I noticed there is a issue with the code gen i will fix that soon (Wrapu should be WrapU, etc)

**Comment by iMrShadow** [comment]
Interesting: I am not sure if it's from DirectXTex or from the wrapper, but the loader crashes on some DDS files, and it's inconsistent. 
[Examples.zip](https://github.com/user-attachments/files/15958195/Examples.zip)

The crash message is ```Exception has occurred: CLR/System.AccessViolationException
An unhandled exception of type 'System.AccessViolationException' occurred in Hexa.NET.DirectXTex.dll: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'```

**Comment by JunaMeinhold** [comment]
idk, the wrapper is very very thin, and only forwards calls to the actual implementation

**Comment by JunaMeinhold** [comment]
both files work on my machine, strange. It might be something on your side.

**Comment by iMrShadow** [comment]
Yeah, the root of the problem has been found. It's interesting why it didn't happen in earlier versions...Hmm

It was a memory leak, because I load the image twice, but I was releasing the memory in only 1 segment (i need to change this behaviour).

**Comment by JunaMeinhold** [comment]
I usually do something like this to prevent issues and memory leaks
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/3d322050-5ff1-4a41-b83c-fe52067dbf94)

**Comment by iMrShadow** [comment]
Update: Actually, I pin-pointed the issue. For some reason it works perfectly fine with LoadFromDDSMemory, but with LoadFromDDSFile sometimes it crashes (and it always crashes with those images I sent). I have no idea why that happens, it's very odd. I also tested these files with your Example project - it also crashes there. (Edit: The above segment also doesn't work - it throws an exception).

It might have to do something with this [segment](https://github.com/HexaEngine/Hexa.NET.DirectXTex/blob/b79e1b4c85d53812ce00cc000cb239d64603236e/Hexa.NET.DirectXTex/Generated/Functions.000.cs#L2599) but i am not exactly sure...

**Comment by JunaMeinhold** [comment]
no issues
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/3e097249-1258-44a8-badc-f6b9b5f1b04d)

**Comment by iMrShadow** [comment]
What...(i dont have the file opened anywhere)
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/22393274/0e10ddd4-d183-4e60-83bc-9396410dd788)

**Comment by JunaMeinhold** [comment]
Okay that only happens when a heap corruption occurs

**Comment by iMrShadow** [comment]
I am gonna restart the PC, this is very weird

**Comment by iMrShadow** [comment]
Same thing. Can it be the Visual Studio setup, despite not changing anything from this project?
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/22393274/a3bd388c-8b6c-4fd2-abbe-429fa1e4f047)

**Comment by JunaMeinhold** [comment]
please enable this
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/7c61b88c-4962-4685-accd-15e82f52689d)
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/3a968084-1f3e-483b-91b6-bb1292a0a936)

**Comment by JunaMeinhold** [comment]
and verify that image is not null after creation
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/4824525b-c7e0-4b74-a0a5-dd89ba327078)

**Comment by iMrShadow** [comment]
Native debugging is enabled. And the image is not null
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/22393274/3d00bc2e-b287-4748-9b03-c62752908301)

**Comment by JunaMeinhold** [comment]
which OS do you have?

**Comment by iMrShadow** [comment]
Windows 10, a slightly older feature update, but i doubt it's from there

Also, could the problem be from here?
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/22393274/5956a367-b712-4a59-bec6-dcf4271844a1)

**Comment by JunaMeinhold** [comment]
no, this code is exactly the same as in my ImGui wrapper and I (and other people) never had issues with that. it's simple string marshalling but with stackalloc if the string is short enough to fit in.

**Comment by JunaMeinhold** [comment]
I'm on win11, give me a minute i will try it on my win 10 laptop

**Comment by iMrShadow** [comment]
That is super interesting. It should not be a hardware problem, I have R5 2600 CPU. I frankly have no idea what's happening. LoadFromDDSMemory works as expected (i first read all bytes from the file).

This code works correctly.

```cs
unsafe public static ImageProperties GetDDSProperties(string ddsFilePath, DDSFlags flags = DDSFlags.None)
    {
        ScratchImage image = GetDDSImage(ByteFunctions.LoadTexture(ddsFilePath), flags);
...
    }
unsafe public static ScratchImage GetDDSImage(byte[] array, DDSFlags flags = DDSFlags.None)
    {
        GCHandle handle = GCHandle.Alloc(array, GCHandleType.Pinned);
        try
        {
            ScratchImage image = DirectXTex.CreateScratchImage();
            TexMetadata metadata;

            // Obtain a pointer to the data
            IntPtr ptr = handle.AddrOfPinnedObject();
            DirectXTex.LoadFromDDSMemory((void*)ptr, (nuint)array.Length, flags, &metadata, image);
            return image;
        }
        finally
        {
            // Release the handle to allow the garbage collector to reclaim the memory
            handle.Free();
        }
    }
```

**Comment by JunaMeinhold** [comment]
very strange on my old win 10 machine everything works just fine, and i freshly downloaded it. 
(Microsoft Windows 10.0.19045.3031, from May 23, 2023)

**Comment by iMrShadow** [comment]
Great...I am out of ideas. It could very well be my OS version (19042.1526). 
At least there is a workaround for now. Thank you very much for the help!

One final debugging option is to commit my changes to my project and see if it works for someone else

**Comment by JunaMeinhold** [comment]
maybe try these in an admin console:
sfc /scannow (https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e)
Dism /Online /Cleanup-Image /ScanHealth
Dism /Online /Cleanup-Image /RestoreHealth
(https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/what-is-dism?view=windows-11)

**Comment by iMrShadow** [comment]
sfc scanned some corrupt files and fixed them. I'll restart again

Update: No effect. Apparently the "corrupt files" were the windows start up sound (I used a custom Windows 95 start up sound)

**Comment by JunaMeinhold** [comment]
Okay I'll make a vm ready and make tests again. (with your exact version)

**Comment by iMrShadow** [comment]
Thanks, I don't think there was need to. 

I commited all of my updates. Here's a [link](https://github.com/iMrShadow/DDS-D3DTX-Converter/tree/main/DDS_D3DTX_Converter_GUI/DDS_D3DTX_Converter) to the project that uses your wrapper.

Update: To use it - just put the dds files i sent you in a different folder. Using my app, open the folder containing them and just click on them in the gridview.

**Comment by JunaMeinhold** [comment]
It works... I also have a older win version installed so it can't be that one
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/293fcd8e-e276-4bf3-99bd-d7fdbc940e72)
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/06db1559-3434-4df9-9cc2-6b7a1b47aeb6)

**Comment by JunaMeinhold** [comment]
another question what is your .net 8 version?
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/8dc1cf8b-6b00-4e27-966b-4e641c38ef76)

**Comment by iMrShadow** [comment]
It's bizarre that it works for you.

My .NET Version is 8.0.202

**Comment by JunaMeinhold** [comment]
try updating it with the visual studio installer or manually

**Comment by JunaMeinhold** [comment]
(it could be because I disabled runtime marshalling and your version has a bug with that feature)

**Comment by iMrShadow** [comment]
Give me a couple of minutes, I am updating Visual Studio too

**Comment by iMrShadow** [comment]
I upgraded to the latest version - no success. It could be the runtime marshalling thing you mentioned

**Comment by JunaMeinhold** [comment]
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/3c64c379-40ed-4336-9db0-84c90217ff05)
![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/5ad4fee4-a3c6-4e83-934e-ca01c421d056)

**Comment by JunaMeinhold** [comment]
And for maximum compatibility set this option in the generator settings and run the generator

![image](https://github.com/HexaEngine/Hexa.NET.DirectXTex/assets/46632782/e774b1a3-4779-43a5-acd9-acb8d59c21c4)

**Comment by iMrShadow** [comment]
I checked the assembly info, i edited the json and ran the Generator, it's not from them either...hmm. Super strange stuff

If you want - I can close this issue now. This seems like a very strange bug which probably only affects me, and there's a workaround too

**Comment by JunaMeinhold** [comment]
Weirdest bug I ever had in my 5 years of programming. The only thing we could do is compare asm code from the disassembly but that's way to deep. If you have any other problems I'm always happy to help. (you can close the issue)

**Comment by iMrShadow** [comment]
The only thing that comes to my mind is the C/C++ compiler I am using, but as you said - at this point it's too deep.

Thank you very much for the help! I appreciate the time you spent trying to figure out what was wrong. If I somehow manage to fix it, I will let you know

I am closing the issue
