### ISSUE TITLE
Question: Reducing library size

### ISSUE THREAD

**Issue by iMrShadow** [HexaEngine/Hexa.NET.DirectXTex#3]
Hi!

I noticed this a little bit late, but the project utilizes Silk.NET, which its assemblies take around 40MBs of space. That doubles the size of my app in my case.

I tried trimming to see what build option would be the best, but the app fails to start.

Is there anything that can be done it? Thanks

**Comment by JunaMeinhold** [comment]
I made a standalone version https://www.nuget.org/packages/Hexa.NET.DirectXTex.Standalone/1.0.0

**Comment by iMrShadow** [comment]
Wow, that was fast!

Thanks a lot, I am closing the issue
