### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by iMrShadow** [HexaEngine/Hexa.NET.DirectXTex#4]
Hello!

I don't think this is possible to add or it is in your interest, but can it be added somehow? 

The MacOS support refers to both arm and x86-64 platforms.

Thanks!

**Comment by JunaMeinhold** [comment]
I'll try, but I can't guarantee or test functionality i don't own a MacOS machine

**Comment by JunaMeinhold** [comment]
![image](https://github.com/user-attachments/assets/684d6d2e-3421-4c13-8a9b-570550dac83d)
The gh workflow output looks promising
https://github.com/HexaEngine/Hexa.NET.DirectXTex/actions/runs/10092645833

**Comment by JunaMeinhold** [comment]
Packages are now online:
https://www.nuget.org/packages/Hexa.NET.DirectXTex/1.0.2
https://www.nuget.org/packages/Hexa.NET.DirectXTex.Standalone/1.0.1

**Comment by iMrShadow** [comment]
Wow, I didn't expect this to be fast, let alone possible. Once again, thanks a lot! If there are any issues I will let you know
